name: flutter_arch_todo_vanilla
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^1.4.4

dev_dependencies:
  intl_translation: ^0.17.7
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
